#123 Implemented `regex_replace` custom function
datayoga-io/datayoga pull request #196
Opened 2022-12-06 17:37 UTC by vd2org

2022-12-07 15:23 UTC, spicy-sauce requested changes

2022-12-07 15:23 UTC, spicy-sauce commented on core/README.md
> +| `regex_replace`      | Replaces matched patterns in the string by the given replacement                                                                    | Input: `{"text": "Banana Bannnana"}` <br
Change description to:
Replaces a string that matches a regular expression

2022-12-07 15:51 UTC, vd2org commented on core/README.md
> +| `regex_replace`      | Replaces matched patterns in the string by the given replacement                                                                    | Input: `{"text": "Banana Bannnana"}` <br
✅

2022-12-08 06:05 UTC, spicy-sauce approved these changes

2022-12-08 06:11 UTC, merged