massive performance improvement - only bind the parts of the json that are referenced in the expression.
datayoga-io/datayoga pull request #246
Opened 2023-01-07 18:30 UTC by zalmane

2023-01-07 18:30 UTC, zalmane commented
performance of SQL nested went from 30K/s to 600K/s

2023-01-08 06:28 UTC, spicy-sauce requested changes

2023-01-08 06:28 UTC, spicy-sauce commented on core/tests/tmp_test.py
> +    mp_handler()
seems that was committed by mistake, please remove.

2023-01-08 12:23 UTC, spicy-sauce approved these changes

2023-01-08 12:24 UTC, merged